[package]
name = "fungibleAsset"
version = "1.0.0"
authors = []

[addresses]
  ownerAddress="input_your_address"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
